export const cartActionType = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  INCREASE_ITEM: 'INCREASE_ITEM',
  REDUCE_ITEM: 'REDUCE_ITEM',
  CART_INIT: 'CART_INIT',
};
