export const userActionType = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGGED_IN_INIT: 'LOGGED_IN_INIT',
  LOGGED_IN_SUCCESS: 'LOGGED_IN_SUCCESS',
  LOGGED_IN_ERROR: 'LOGGED_IN_ERROR',
  LOGOUT: 'LOGOUT',
  CLEAN_STATE: 'CLEAN_STATE',
};
